name: EnvSecrets Access

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  env_setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: actions_env

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo ENV
        env:
          MESSAGE: "Hello World"
        run: echo "$MESSAGE"

      - name: Echo Actuall Env
        run: echo "Env variable MY_SAMPLE_AUDIO:- [${{ vars.MY_SAMPLE_AUDIO }}]"

      - name: PrintEnv
        run: printenv
