name: Multi Env Workflow

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    # ðŸ‘‡ choose GitHub Environment based on branch
    environment: ${{ github.ref_name }}
    
    # dev / staging / prod environment must exist
    env:
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      SERVER_USER: ${{ vars.SERVER_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Show where we are testing
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: ${{ github.ref_name }}"
      
