name: Multi Env Workflow

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    # ðŸ‘‡ choose GitHub Environment based on branch
    environment: ${{ github.ref_name }}
    
    # dev / staging / prod environment must exist
    env:
      ENV_MODE: ${{ vars.ENV_MODE }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Show where we are testing
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: $ENV_MODE"
